export const calendarList = {
  solar: {
    language: 'persian',
    calendar: 'jalali',
    weekdays: ['ش', 'ی', 'د', 'س', 'چ', 'پ', 'ج'],
    months: [
      'فروردین',
      'اردیبهشت',
      'خرداد',
      'تیر',
      'مرداد',
      'شهریور',
      'مهر',
      'آبان',
      'آذر',
      'دی',
      'بهمن',
      'اسفند',
    ],
    dir: {
      input: 'rtl',
      picker: 'rtl',
    },
    inputFormat: '',
    displayFormat: '',
  },
  gregorian: {
    language: 'english',
    calendar: 'gregorian',
    weekdays: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    months: [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ],
    dir: {
      input: 'rtl',
      picker: 'ltr',
    },
    inputFormat: '',
    displayFormat: '',
  },
};
